version: '3'
services:
  postgrescinema:
    image: postgres:13
    restart: unless-stopped
    container_name: ${DOCKER_PREFIX}cinemaDB
    environment:
      - POSTGRES_DB=$POSTGRES_DB
      - POSTGRES_USER=$POSTGRES_USER
      - POSTGRES_PASSWORD=$POSTGRES_PASSWORD
    volumes:
      - ./postgres/production:/var/lib/postgresql/data
    networks:
      - AsyncCinema
  rediscinema:
    restart: unless-stopped
    container_name: ${DOCKER_PREFIX}cinemaRedis
    environment:
      - REDIS_PASSWORD=$REDIS_PASSWORD
      - REDIS_PORT=$REDIS_PORT
    build: ./redis/
    volumes:
      - ./redis/production:/data
    networks:
      - AsyncCinema
  elasticcinema01:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.10.2
    container_name: ${DOCKER_PREFIX}cinemaES01
    environment:
      - node.name=elasticcinema01
      - http.port=$ELASTIC_PORT
      - discovery.type=single-node
      - xpack.security.enabled=true
      - ELASTIC_PASSWORD=$ELASTIC_PASSWORD
      - ELASTIC_INDEX=$ELASTIC_INDEX
      - path.repo=/usr/share/elasticsearch/backup
    volumes:
      - ./elastic/production:/usr/share/elasticsearch/data
      - ./elastic/backup:/usr/share/elasticsearch/backup
    networks:
      - AsyncCinema
  etlcinema:
    restart: 'no'
    container_name: ${DOCKER_PREFIX}ETLCinema
    environment:
      - POSTGRES_DB=$POSTGRES_DB
      - POSTGRES_USER=$POSTGRES_USER
      - POSTGRES_PASSWORD=$POSTGRES_PASSWORD
      - POSTGRES_HOST=postgrescinema
      - POSTGRES_SCHEMA=$POSTGRES_SCHEMA
      - REDIS_PREFIX=$REDIS_PREFIX
      - REDIS_HOST=rediscinema
      - REDIS_PORT=$REDIS_PORT
      - REDIS_PASSWORD=$REDIS_PASSWORD
      - ELASTIC_HOST=elasticcinema01
      - ELASTIC_PORT=$ELASTIC_PORT
      - ELASTIC_USER=$ELASTIC_USER
      - ELASTIC_PASSWORD=$ELASTIC_PASSWORD
      - ELASTIC_INDEX=$ELASTIC_INDEX
      - ETL_SIZE_LIMIT=$ETL_SIZE_LIMIT
    build: ./postgres_to_es/
    command: /docker-entrypoint.sh
    networks:
      - AsyncCinema
    depends_on:
      - postgrescinema
      - rediscinema
      - elasticcinema01
  clientapicinema:
    restart: unless-stopped
    container_name: ${DOCKER_PREFIX}clientApi
    environment:
      - REDIS_HOST=rediscinema
      - REDIS_PORT=$REDIS_PORT
      - REDIS_PASSWORD=$REDIS_PASSWORD
      - ELASTIC_HOST=elasticcinema01
      - ELASTIC_PORT=$ELASTIC_PORT
      - ELASTIC_USER=$ELASTIC_USER
      - ELASTIC_PASSWORD=$ELASTIC_PASSWORD
      - ELASTIC_INDEX=$ELASTIC_INDEX
      - UVICORN_PORT=$UVICORN_PORT
    build: ./src/
    command: /docker-entrypoint.sh
    networks:
      - AsyncCinema
    depends_on:
      - rediscinema
      - elasticcinema01
  nginxcinema:
    restart: unless-stopped
    container_name: ${DOCKER_PREFIX}cinemaNginx
    environment:
      - UVICORN_SERVICE_NAME=clientapicinema
      - UVICORN_PORT=$UVICORN_PORT
    build: ./nginx/
    ports:
      - $NGINX_HTTP_PORT:80
    networks: 
      - AsyncCinema
    depends_on:
      - clientapicinema
networks:
  AsyncCinema:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: $DOCKER_NETWORK_ADDRESS
